UserType.create!(name: "District Manager", permission_id: 1)
UserType.create!(name: "Scheduler", permission_id: 2)
UserType.create!(name: "Store Manager", permission_id: 3)
UserType.create!(name: "Staff Pharmacist", permission_id: 4)
UserType.create!(name: "Floater Pharmacist", permission_id: 5)
